services:
  app:
    build: .
    container_name: library-accounting-service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/Library
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - app-network

  postgres:
    container_name: postgres
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: Library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: