spring:
  profiles:
    active: prod

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  server:
    port: 8080

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    tagsSorter: alpha
    docExpansion: none
    operationsSorter: alpha
    persist-authorization: true
    try-it-out-enabled: true